# Домашнее задание №1

# Тимершина Юстина, Золотова Анна, Цемахман Филипп,           Прокопенкова Дарья (БММ184)

# PREPARE DATA

In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [12]:
# подгрузим данные
ratings = pd.read_csv("ratings.csv")
tags= pd.read_csv("tags.csv")
movies = pd.read_csv("movies.csv")

In [13]:
ratings[['userId', 'movieId', 'rating']]

        userId  movieId  rating
0            1        1     4.0
1            1        3     4.0
2            1        6     4.0
3            1       47     5.0
4            1       50     5.0
5            1       70     3.0
6            1      101     5.0
7            1      110     4.0
8            1      151     5.0
9            1      157     5.0
10           1      163     5.0
11           1      216     5.0
12           1      223     3.0
13           1      231     5.0
14           1      235     4.0
15           1      260     5.0
16           1      296     3.0
17           1      316     3.0
18           1      333     5.0
19           1      349     4.0
20           1      356     4.0
21           1      362     5.0
22           1      367     4.0
23           1      423     3.0
24           1      441     4.0
25           1      457     5.0
26           1      480     4.0
27           1      500     3.0
28           1      527     5.0
29           1      543     4.0
...        ...      ...     ...
100806     610   150401     3.0
100807     610   152077     4.0
100808     610   152081     4.0
100809     610   152372     3.5
100810     610   155064     3.5
100811     610   156371     5.0
100812     610   156726     4.5
100813     610   157296     4.0
100814     610   158238     5.0
100815     610   158721     3.5
100816     610   158872     3.5
100817     610   158956     3.0
100818     610   159093     3.0
100819     610   160080     3.0
100820     610   160341     2.5
100821     610   160527     4.5
100822     610   160571     3.0
100823     610   160836     3.0
100824     610   161582     4.0
100825     610   161634     4.0
100826     610   162350     3.5
100827     610   163937     3.5
100828     610   163981     3.5
100829     610   164179     5.0
100830     610   166528     4.0
100831     610   166534     4.0
100832     610   168248     5.0
100833     610   168250     5.0
100834     610   168252     5.0
100835     610   170875     3.0

[100836 rows x 3 columns]

In [14]:
movies['genres'].str.split("|")

0       [Adventure, Animation, Children, Comedy, Fantasy]
1                          [Adventure, Children, Fantasy]
2                                       [Comedy, Romance]
3                                [Comedy, Drama, Romance]
4                                                [Comedy]
5                               [Action, Crime, Thriller]
6                                       [Comedy, Romance]
7                                   [Adventure, Children]
8                                                [Action]
9                           [Action, Adventure, Thriller]
10                               [Comedy, Drama, Romance]
11                                       [Comedy, Horror]
12                       [Adventure, Animation, Children]
13                                                [Drama]
14                           [Action, Adventure, Romance]
15                                         [Crime, Drama]
16                                       [Drama, Romance]
17                                               [Comedy]
18                                               [Comedy]
19               [Action, Comedy, Crime, Drama, Thriller]
20                              [Comedy, Crime, Thriller]
21              [Crime, Drama, Horror, Mystery, Thriller]
22                              [Action, Crime, Thriller]
23                                        [Drama, Sci-Fi]
24                                       [Drama, Romance]
25                                                [Drama]
26                                      [Children, Drama]
27                                       [Drama, Romance]
28           [Adventure, Drama, Fantasy, Mystery, Sci-Fi]
29                                         [Crime, Drama]
                              ...
9712                            [Comedy, Fantasy, Sci-Fi]
9713         [Action, Adventure, Comedy, Fantasy, Sci-Fi]
9714                                       [Crime, Drama]
9715                                    [Comedy, Romance]
9716                                             [Comedy]
9717                         [Adventure, Comedy, Fantasy]
9718                                      [Comedy, Drama]
9719                                        [Documentary]
9720                        [Action, Adventure, Thriller]
9721                            [Action, Crime, Thriller]
9722                                     [Action, Sci-Fi]
9723                               [Comedy, Crime, Drama]
9724                                   [Sci-Fi, Thriller]
9725                                     [Drama, Romance]
9726                                             [Comedy]
9727                                              [Drama]
9728                                              [Drama]
9729                                          [Animation]
9730                                        [Documentary]
9731                  [Action, Adventure, Comedy, Sci-Fi]
9732                  [Action, Animation, Comedy, Sci-Fi]
9733                                   [Animation, Drama]
9734                                      [Comedy, Drama]
9735                                          [Animation]
9736                                        [Documentary]
9737                 [Action, Animation, Comedy, Fantasy]
9738                         [Animation, Comedy, Fantasy]
9739                                              [Drama]
9740                                  [Action, Animation]
9741                                             [Comedy]
Name: genres, Length: 9742, dtype: object

In [15]:
# джойним / мержим два датафрейма
# ссылка на документацию: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.merge.html

movies = movies.merge(ratings, on = 'movieId', how = 'inner')

In [16]:
# cоздаем датасет содержащий юзеров, фильмы и оценки которые они проставили , чтоб в дальнейшем искать похожих при помощи коллабаративной фильтрации
movies = movies[['userId','movieId','rating']]
movies

        userId  movieId  rating
0            1        1     4.0
1            5        1     4.0
2            7        1     4.5
3           15        1     2.5
4           17        1     4.5
5           18        1     3.5
6           19        1     4.0
7           21        1     3.5
8           27        1     3.0
9           31        1     5.0
10          32        1     3.0
11          33        1     3.0
12          40        1     5.0
13          43        1     5.0
14          44        1     3.0
15          45        1     4.0
16          46        1     5.0
17          50        1     3.0
18          54        1     3.0
19          57        1     5.0
20          63        1     5.0
21          64        1     4.0
22          66        1     4.0
23          68        1     2.5
24          71        1     5.0
25          73        1     4.5
26          76        1     0.5
27          78        1     4.0
28          82        1     2.5
29          86        1     4.0
...        ...      ...     ...
100806     596   188301     4.0
100807     318   188675     3.5
100808     212   188751     4.5
100809     514   188797     4.0
100810     318   188833     4.5
100811     338   189043     2.5
100812     338   189111     3.0
100813     184   189333     4.0
100814     248   189333     3.5
100815     318   189381     2.5
100816     210   189547     1.0
100817     462   189713     2.5
100818      50   190183     3.5
100819     338   190207     1.5
100820     338   190209     4.0
100821     338   190213     1.0
100822     338   190215     1.5
100823     338   190219     1.0
100824     338   190221     1.0
100825     184   191005     4.5
100826     184   193565     3.5
100827     184   193567     3.0
100828     184   193571     4.0
100829     184   193573     4.0
100830     184   193579     3.5
100831     184   193581     4.0
100832     184   193583     3.5
100833     184   193585     3.5
100834     184   193587     3.5
100835     331   193609     4.0

[100836 rows x 3 columns]

# SVD

Дальше мы работаем с SVD. Для этого устанавливаем surprise 

Подгружаем массивы данных в тетрадку

Создаем reader 

Обучаем меодель SVD методом cross validation разбивая быорку на 5 отрезков

In [18]:
pip install surprise

Collecting surprise
  Downloading https://files.pythonhosted.org/packages/61/de/e5cba8682201fcf9c3719a6fdda95693468ed061945493dea2dd37c5618b/surprise-0.1-py2.py3-none-any.whl
Collecting scikit-surprise (from surprise)
  Downloading https://files.pythonhosted.org/packages/f5/da/b5700d96495fb4f092be497f02492768a3d96a3f4fa2ae7dea46d4081cfa/scikit-surprise-1.1.0.tar.gz (6.4MB)
    100% |████████████████████████████████| 6.5MB 2.7MB/s ta 0:00:011
Collecting joblib>=0.11 (from scikit-surprise->surprise)
  Downloading https://files.pythonhosted.org/packages/28/5c/cf6a2b65a321c4a209efcdf64c2689efae2cb62661f8f6f4bb28547cf1bf/joblib-0.14.1-py2.py3-none-any.whl (294kB)
    100% |████████████████████████████████| 296kB 2.2MB/s ta 0:00:01
Requirement already satisfied: numpy>=1.11.2 in /anaconda3/lib/python3.7/site-packages (from scikit-surprise->surprise) (1.16.2)
Requirement already satisfied: scipy>=1.0.0 in /anaconda3/lib/python3.7/site-packages (from scikit-surprise->surprise) (1.2.1)
Requirement already satisfied: six>=1.10.0 in /anaconda3/lib/python3.7/site-packages (from scikit-surprise->surprise) (1.12.0)
Building wheels for collected packages: scikit-surprise
  Building wheel for scikit-surprise (setup.py) ... done
  Stored in directory: /Users/justina/Library/Caches/pip/wheels/cc/fa/8c/16c93fccce688ae1bde7d979ff102f7bee980d9cfeb8641bcf
Successfully built scikit-surprise
Installing collected packages: joblib, scikit-surprise, surprise
Successfully installed joblib-0.14.1 scikit-surprise-1.1.0 surprise-0.1
Note: you may need to restart the kernel to use updated packages.

In [19]:
from surprise import SVD
from surprise import Dataset, Reader
from surprise.model_selection import cross_validate

In [20]:
reader=Reader(rating_scale=(1,5))
data = Dataset.load_from_df(movies, reader)

In [21]:
model = SVD()

In [22]:
cross_validate(model, data, measures=['MSE', 'MAE'], cv=8, verbose=True)

Evaluating MSE, MAE of algorithm SVD on 8 split(s).

                  Fold 1  Fold 2  Fold 3  Fold 4  Fold 5  Fold 6  Fold 7  Fold 8  Mean    Std
MSE (testset)     0.7489  0.7516  0.7670  0.7542  0.7326  0.7597  0.7723  0.7698  0.7570  0.0123
MAE (testset)     0.6652  0.6662  0.6728  0.6662  0.6589  0.6656  0.6754  0.6748  0.6681  0.0053
Fit time          5.35    5.43    5.85    5.86    7.47    6.45    6.37    7.51    6.29    0.78
Test time         0.09    0.08    0.08    0.09    0.16    0.08    0.09    0.08    0.09    0.03

{'test_mse': array([0.74889011, 0.75156295, 0.76698195, 0.75424977, 0.73258922,
        0.75972815, 0.77228637, 0.76976234]),
 'test_mae': array([0.66519385, 0.66615985, 0.67276994, 0.66617648, 0.65893817,
        0.66564068, 0.67539062, 0.67475926]),
 'fit_time': (5.347649097442627,
  5.431548118591309,
  5.850673198699951,
  5.86156702041626,
  7.467051982879639,
  6.449067831039429,
  6.367442846298218,
  7.51041316986084),
 'test_time': (0.092041015625,
  0.07790899276733398,
  0.07903599739074707,
  0.08806967735290527,
  0.16104698181152344,
  0.08038091659545898,
  0.09312701225280762,
  0.07950997352600098)}

MSE=0,7570

MAE=0,6681